server:
  port: 8080
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ketangpai?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  type-aliases-package: ketangpai.entity
  mapper-locations: classpath:dao/*Dao.xml
app:
  uploadFolder: D://uploadFiles/
  previewPath: http://127.0.0.1:8080/
web:
  upload-path: D://uploadFiles/
  